create table users (
    id            bigint generated by default as identity primary key,
    email         varchar(320) not null,
    password_hash varchar(100) not null,
    full_name     varchar(150) not null,
    role          varchar(16)  not null,
    created_at    timestamptz  not null,
    constraint uk_users_email unique (email)
);
