create table spaces (
    id          bigint generated by default as identity primary key,
    name        varchar(120)  not null,
    type        varchar(24)   not null,
    capacity    integer       not null,
    location    varchar(120)  not null,
    hourly_rate numeric(10,2) not null,
    active      boolean       not null default true,
    version     bigint,
    constraint chk_spaces_capacity check (capacity > 0),
    constraint chk_spaces_rate check (hourly_rate >= 0)
);
