create table reservations (
    id          bigint generated by default as identity primary key,
    space_id    bigint        not null,
    user_id     bigint        not null,
    start_time  timestamptz   not null,
    end_time    timestamptz   not null,
    status      varchar(20)   not null,
    price_total numeric(12,2) not null,
    payment_ref varchar(64),
    created_at  timestamptz   not null,
    version     bigint,
    constraint fk_res_space foreign key (space_id) references spaces (id),
    constraint fk_res_user  foreign key (user_id)  references users (id),
    constraint chk_res_window check (end_time > start_time)
);

create index ix_res_user_start on reservations (user_id, start_time);
create index ix_res_status on reservations (status);
